### GET request to example server
GET http://127.0.0.1:8080/ping
    ?generated-in=PyCharm

### POST request to local server
POST http://127.0.0.1:8080/chat
Content-Type: application/json
Accept: application/json

{
  "query": "请讲一个笑话"
}

### 创建APP
POST http://127.0.0.1:8080/app
Content-Type: application/json
Accept: application/json

{
}

### 获取APP
GET http://127.0.0.1:8080/app/d44f3f42-9e81-4445-8c38-41342ae6e7b5
Content-Type: application/json
Accept: application/json

### 修改APP
POST http://127.0.0.1:8080/app/d44f3f42-9e81-4445-8c38-41342ae6e7b5
Content-Type: application/json
Accept: application/json

### 删除APP
POST http://127.0.0.1:8080/app/d44f3f42-9e81-4445-8c38-41342ae6e7b5/delete
Content-Type: application/json
Accept: application/json



